version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak-x:16.1.1
    restart: unless-stopped
    command: start --auto-build
    environment:
    env_file: .env.keycloak
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
      - shared

  keycloak-postgres:
    image: docker.io/postgres:14-alpine
    restart: unless-stopped
    env_file: .env.keycloak-postgres
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared

networks:
  shared:
    external: true