include:
  - images/*/.gitlab-ci.yml

stages:
  - build_images
  - plan

plan:
  stage: plan
  image: docker.home.giodamelio.com/giodamelio/homelab/builder:latest
  script:
    - chmod 600 $DOCKER_SSH_KEY
    - mkdir -p ~/.ssh
    - printf "Host 10.0.0.198\n\tIdentityFile %s" $DOCKER_SSH_KEY >> ~/.ssh/config
    - cd tf/
    - terraform init
    - terraform plan

#### Job templates ####
.docker_image:
  stage: build_images
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}/images/${IMAGE_NAME}/"
      --dockerfile "${CI_PROJECT_DIR}/images/${IMAGE_NAME}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:latest"
  only:
    changes:
      - ${CI_PROJECT_DIR}/.gitlab-ci.yml
      - ${CI_PROJECT_DIR}/images/${IMAGE_NAME}/*
      - ${CI_PROJECT_DIR}/images/${IMAGE_NAME}/**/*
