version: '3.8'
services:
  gitlab:
    image: docker.io/gitlab/gitlab-ce:14.8.2-ce.0
    volumes:
      - ./data/config:/etc/gitlab:Z
      - ./data/logs:/var/log/gitlab:Z
      - ./data/data:/var/opt/gitlab:Z
    networks:
      - shared

networks:
  shared:
    external: true