version: '3.8'
services:
  gitlab:
    image: docker.io/gitlab/gitlab-ce:14.8.2-ce.0
    restart: unless-stopped
    volumes:
      - ./data/config:/etc/gitlab:Z
      - ./data/logs:/var/log/gitlab:Z
      - ./data/data:/var/opt/gitlab:Z
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Run behind reverse proxy
        external_url 'https://gitlab.home.giodamelio.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false

        # Email Server Settings
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.fastmail.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "${GITLAB_SMTP_USER_NAME}"
        gitlab_rails['smtp_password'] = "${GITLAB_SMTP_PASSWORD}"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'

        # Email Settings
        gitlab_rails['gitlab_email_from'] = 'gitlab@giodamelio.com'
        gitlab_rails['gitlab_email_display_name'] = 'Homelab Gitlab'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@giodamelio.com'

        # Backup settings
        gitlab_rails['backup_keep_time'] = 2592000 # 30 Days in seconds
        gitlab_rails['backup_upload_connection'] = {
          'provider' => 'AWS',
          'endpoint' => 'http://minio:9000',
          'aws_access_key_id' => '${GITLAB_BACKUP_AWS_ACCESS_KEY_ID}',
          'aws_secret_access_key' => '${GITLAB_BACKUP_AWS_SECRET_ACCESS_KEY}',
          'path_style' => true,
        }
        gitlab_rails['backup_upload_remote_directory'] = '${GITLAB_BACKUP_AWS_BUCKET}'
    networks:
      - shared

networks:
  shared:
    external: true