services:
  - name: "Admin"
    icon: "fas fa-server"
    items:
      - name: "Cockpit"
        logo: "assets/logos/cockpit.png"
        subtitle: "Linux Admin Panel"
        url: "https://cockpit.home.giodamelio.com"
      - name: "Keycloak"
        logo: "assets/logos/keycloak.png"
        subtitle: "Identity and Access Management Solution"
        url: "https://keycloak.home.giodamelio.com/admin/master/console"
      # - name: "InfluxDB"
      #   logo: "assets/logos/influxdb.png"
      #   subtitle: "Metrics"
      #   url: "https://influxdb.home.giodamelio.com"
  - name: "Data"
    icon: "fas fa-database"
    items:
      - name: "Minio"
        logo: "assets/logos/minio.png"
        subtitle: "S3 Compatable Object Store"
        url: "https://minio.home.giodamelio.com"