version: '3.8'
services:
  proxy:
    image: docker.home.giodamelio/proxy
    build: ../../images/proxy/
    restart: unless-stopped
    env_file: .env.route53
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./data/data:/data:Z
    networks:
      - shared

  test:
    image: docker.io/traefik/whoami:latest
    restart: unless-stopped
    networks:
      - shared

networks:
  shared:
    external: true