all:
  children:
    kube_nodes:
      hosts:
        10.1.0.66: # node1
        10.1.0.68: # node2
        10.1.0.67: # node3
      vars:
        ansible_user: debian
        ansible_python_interpreter: /usr/bin/python3