all:
  hosts:
    xen_orchestra:
      ansible_host: 10.1.0.70
  children:
    kube_nodes:
      hosts:
        node1:
          ansible_host: 10.1.0.66
        node2:
          ansible_host: 10.1.0.68
        node3:
          ansible_host: 10.1.0.67
  vars:
    ansible_user: debian
    ansible_python_interpreter: /usr/bin/python3